version: "3.7"
services:
  php:
    build: ./php
    ports:
      - 8080:80
    volumes:
      - ../src/:/var/www/html/
      - ../db/:/var/lib/sqlite3/
      - ./php/php.ini:/usr/local/etc/php/php.ini
